import ExceptionType from '#models/exception_type'
import { BaseSeeder } from '@adonisjs/lucid/seeders'
import { DateTime } from 'luxon'

export default class extends BaseSeeder {
  async run() {
    const exceptionTypes = [
      {
        exceptionTypeSlug: 'absence-from-work',
        exceptionTypeTypeName: 'Falta a laborar',
        exceptionTypeIcon: 'icon_absence_from_work',
        exceptionTypeIsGeneral: 0,
        exceptionTypeNeedCheckInTime: 0,
        exceptionTypeNeedCheckOutTime: 0,
        exceptionTypeNeedReason: 1,
        exceptionTypeNeedEnjoymentOfSalary: 1,
        exceptionTypeNeedPeriodInDays: 1,
        exceptionTypeNeedPeriodInHours: 0,
        exceptionTypeActive: 1,
        exceptionTypeCanMasive: 1,
      },
      {
        exceptionTypeSlug: 'late-arrival',
        exceptionTypeTypeName: 'Llegadar tarde',
        exceptionTypeIcon: 'icon_late_arrival',
        exceptionTypeIsGeneral: 1,
        exceptionTypeNeedCheckInTime: 1,
        exceptionTypeNeedCheckOutTime: 0,
        exceptionTypeNeedReason: 1,
        exceptionTypeNeedEnjoymentOfSalary: 0,
        exceptionTypeNeedPeriodInDays: 1,
        exceptionTypeNeedPeriodInHours: 0,
        exceptionTypeActive: 1,
        exceptionTypeCanMasive: 0,
      },
      {
        exceptionTypeSlug: 'early-departure',
        exceptionTypeTypeName: 'Salir temprano',
        exceptionTypeIcon: 'icon_early_departure',
        exceptionTypeIsGeneral: 1,
        exceptionTypeNeedCheckInTime: 0,
        exceptionTypeNeedCheckOutTime: 1,
        exceptionTypeNeedReason: 1,
        exceptionTypeNeedEnjoymentOfSalary: 0,
        exceptionTypeNeedPeriodInDays: 1,
        exceptionTypeNeedPeriodInHours: 0,
        exceptionTypeActive: 1,
        exceptionTypeCanMasive: 0,
      },
      {
        exceptionTypeSlug: 'leaving-during-work-hours',
        exceptionTypeTypeName: 'Salir en horas laborales',
        exceptionTypeIcon: 'icon_leaving_during_work_hours',
        exceptionTypeIsGeneral: 0,
        exceptionTypeNeedCheckInTime: 0,
        exceptionTypeNeedCheckOutTime: 0,
        exceptionTypeNeedReason: 1,
        exceptionTypeNeedEnjoymentOfSalary: 0,
        exceptionTypeNeedPeriodInDays: 0,
        exceptionTypeNeedPeriodInHours: 1,
        exceptionTypeActive: 1,
        exceptionTypeCanMasive: 0,
      },
      {
        exceptionTypeSlug: 'working-during-non-working-hours',
        exceptionTypeTypeName: 'Trabajar fuera de horario',
        exceptionTypeIcon: 'icon_working_during_non_working_hours',
        exceptionTypeIsGeneral: 0,
        exceptionTypeNeedCheckInTime: 0,
        exceptionTypeNeedCheckOutTime: 0,
        exceptionTypeNeedReason: 1,
        exceptionTypeNeedEnjoymentOfSalary: 1,
        exceptionTypeNeedPeriodInDays: 1,
        exceptionTypeNeedPeriodInHours: 1,
        exceptionTypeActive: 1,
        exceptionTypeCanMasive: 0,
      },
      {
        exceptionTypeSlug: 'vacation',
        exceptionTypeTypeName: 'Día de vacaciones',
        exceptionTypeIcon: 'icon_vacation',
        exceptionTypeIsGeneral: 0,
        exceptionTypeNeedCheckInTime: 0,
        exceptionTypeNeedCheckOutTime: 0,
        exceptionTypeNeedReason: 1,
        exceptionTypeNeedEnjoymentOfSalary: 0,
        exceptionTypeNeedPeriodInDays: 0,
        exceptionTypeNeedPeriodInHours: 0,
        exceptionTypeActive: 1,
        exceptionTypeCanMasive: 0,
      },
      {
        exceptionTypeSlug: 'overtime',
        exceptionTypeTypeName: 'Horas extra',
        exceptionTypeIcon: 'icon_overtime',
        exceptionTypeIsGeneral: 0,
        exceptionTypeNeedCheckInTime: 0,
        exceptionTypeNeedCheckOutTime: 0,
        exceptionTypeNeedReason: 1,
        exceptionTypeNeedEnjoymentOfSalary: 0,
        exceptionTypeNeedPeriodInDays: 0,
        exceptionTypeNeedPeriodInHours: 0,
        exceptionTypeActive: 1,
        exceptionTypeCanMasive: 0,
      },
      {
        exceptionTypeSlug: 'rest-day',
        exceptionTypeTypeName: 'Día de descanso',
        exceptionTypeIcon: 'icon_absence_from_work',
        exceptionTypeIsGeneral: 0,
        exceptionTypeNeedCheckInTime: 0,
        exceptionTypeNeedCheckOutTime: 0,
        exceptionTypeNeedReason: 0,
        exceptionTypeNeedEnjoymentOfSalary: 0,
        exceptionTypeNeedPeriodInDays: 0,
        exceptionTypeNeedPeriodInHours: 0,
        exceptionTypeActive: 1,
        exceptionTypeCanMasive: 1,
      },
      {
        exceptionTypeSlug: 'nuevo-ingreso',
        exceptionTypeTypeName: 'Nuevo ingreso (Capacitación)',
        exceptionTypeIcon: 'icon_absence_from_work',
        exceptionTypeIsGeneral: 0,
        exceptionTypeNeedCheckInTime: 0,
        exceptionTypeNeedCheckOutTime: 0,
        exceptionTypeNeedReason: 0,
        exceptionTypeNeedEnjoymentOfSalary: 0,
        exceptionTypeNeedPeriodInDays: 1,
        exceptionTypeNeedPeriodInHours: 0,
        exceptionTypeActive: 1,
        exceptionTypeCanMasive: 1,
      },
      {
        exceptionTypeSlug: 'falta-por-incapacidad',
        exceptionTypeTypeName: 'Incapacidad',
        exceptionTypeIcon: 'icon_absence_from_work',
        exceptionTypeIsGeneral: 0,
        exceptionTypeNeedCheckInTime: 0,
        exceptionTypeNeedCheckOutTime: 0,
        exceptionTypeNeedReason: 1,
        exceptionTypeNeedEnjoymentOfSalary: 0,
        exceptionTypeNeedPeriodInDays: 1,
        exceptionTypeNeedPeriodInHours: 0,
        exceptionTypeActive: 1,
        exceptionTypeCanMasive: 0,
      },
      {
        exceptionTypeSlug: 'descanso-laborado',
        exceptionTypeTypeName: 'Trabajar en día de descanso',
        exceptionTypeIcon: 'icon_absence_from_work',
        exceptionTypeIsGeneral: 0,
        exceptionTypeNeedCheckInTime: 0,
        exceptionTypeNeedCheckOutTime: 0,
        exceptionTypeNeedReason: 1,
        exceptionTypeNeedEnjoymentOfSalary: 1,
        exceptionTypeNeedPeriodInDays: 0,
        exceptionTypeNeedPeriodInHours: 0,
        exceptionTypeActive: 1,
        exceptionTypeCanMasive: 0,
      },
      {
        exceptionTypeSlug: 'skip-checkout',
        exceptionTypeTypeName: 'Salir sin marcar salida',
        exceptionTypeIcon: 'icon_absence_from_work',
        exceptionTypeIsGeneral: 0,
        exceptionTypeNeedCheckInTime: 0,
        exceptionTypeNeedCheckOutTime: 0,
        exceptionTypeNeedReason: 1,
        exceptionTypeNeedEnjoymentOfSalary: 0,
        exceptionTypeNeedPeriodInDays: 0,
        exceptionTypeNeedPeriodInHours: 0,
        exceptionTypeActive: 1,
        exceptionTypeCanMasive: 0,
      },
      {
        exceptionTypeSlug: 'skip-checkin',
        exceptionTypeTypeName: 'Iniciar turno sin marcar entrada',
        exceptionTypeIcon: 'icon_absence_from_work',
        exceptionTypeIsGeneral: 0,
        exceptionTypeNeedCheckInTime: 0,
        exceptionTypeNeedCheckOutTime: 0,
        exceptionTypeNeedReason: 1,
        exceptionTypeNeedEnjoymentOfSalary: 0,
        exceptionTypeNeedPeriodInDays: 0,
        exceptionTypeNeedPeriodInHours: 0,
        exceptionTypeActive: 1,
        exceptionTypeCanMasive: 0,
      },
    ]

    for (const exceptionType of exceptionTypes) {
      const { exceptionTypeSlug, ...exceptionTypeData } = exceptionType
      await ExceptionType.firstOrCreate(
        { exceptionTypeSlug },
        {
          ...exceptionTypeData,
          exceptionTypeCanMasive: Boolean(exceptionTypeData.exceptionTypeCanMasive),
          exceptionTypeCreatedAt: DateTime.now(),
        }
      )
    }
  }
}
