// ─── Mapa congelado del estado PREVIO (dejado por 1788282413066000) ──────────
// Fuente: volcado real de sae_pruebas, 2026-09-04.
// Sirve de base para el down(); null = módulo suelto (sin grupo en ese momento).
export const PREVIOUS_STATE = [
    { slug: 'employees',                        groupKey: 'empresa',         order: 10  },
    { slug: 'departments',                      groupKey: 'empresa',         order: 20  },
    { slug: 'positions',                        groupKey: 'empresa',         order: 30  },
    { slug: 'vacations',                        groupKey: 'configuraciones', order: 40  },
    { slug: 'users',                            groupKey: 'empresa',         order: 50  },
    { slug: 'departments-attendance-monitor',   groupKey: 'reportes',        order: 60  },
    { slug: 'employees-attendance-monitor',     groupKey: 'reportes',        order: 70  },
    { slug: 'roles-and-permissions',            groupKey: 'configuraciones', order: 80  },
    { slug: 'shifts',                           groupKey: 'configuraciones', order: 120 },
    { slug: 'holidays',                         groupKey: 'calendarios',     order: 130 },
    { slug: 'system-settings',                  groupKey: 'configuraciones', order: 140 },
    { slug: 'documents-expiration-matrix',      groupKey: 'reportes',        order: 190 },
    { slug: 'proceeding-file-types',            groupKey: 'otros',           order: 210 },
    { slug: 'shift-exception-requests',         groupKey: 'otros',           order: 220 },
    { slug: 'organization-chart',               groupKey: 'empresa',         order: 250 },
    { slug: 'birthdays-calendar',               groupKey: 'calendarios',     order: 260 },
    { slug: 'vacations-calendar',               groupKey: 'calendarios',     order: 270 },
    { slug: 'work-anniversaries-calendar',      groupKey: 'calendarios',     order: 280 },
    { slug: 'supplies',                         groupKey: 'empresa',         order: 290 },
    { slug: 'zonas',                            groupKey: 'configuraciones', order: 300 },
    { slug: 'permissions-history',              groupKey: 'reportes',        order: 310 },
    { slug: 'avisos-y-noticias',                groupKey: 'empresa',         order: 320 },
    { slug: 'puntos-de-acceso',                 groupKey: 'zksync',          order: 330 },
    { slug: 'sucursales',                       groupKey: 'empresa',         order: 340 },
    { slug: 'assessment-templates',             groupKey: 'empresa',         order: 350 },
    { slug: 'certifications',                   groupKey: 'empresa',         order: 360 },
    { slug: 'employee-lactation-periods',       groupKey: 'empresa',         order: 370 },
    { slug: 'repse-registrations',              groupKey: 'empresa',         order: 380 },
    { slug: 'working-time-overrides',           groupKey: 'configuraciones', order: 390 },
    { slug: 'traumatic-event-reports',          groupKey: 'nom-035',         order: 400 },
    { slug: 'traumatic-event-reports-registry', groupKey: 'nom-035',         order: 410 },
    { slug: 'compliance',                       groupKey: 'nom-035',         order: 420 },
    { slug: 'retention-policy',                 groupKey: 'nom-035',         order: 430 },
    { slug: 'attention-program',                groupKey: 'nom-035',         order: 440 },
    { slug: 'nom035-disclosure',                groupKey: 'nom-035',         order: 450 },
    { slug: 'sensitive-data-access-log',        groupKey: 'nom-035',         order: 460 },
    { slug: 'telework-policy',                  groupKey: 'nom-037',         order: 470 },
    { slug: 'reform-simulation',                groupKey: 'configuraciones', order: 480 },
    { slug: 'repse-providers',                  groupKey: null,              order: 490 },
    { slug: 'regulatory-coverage',              groupKey: 'plataforma',      order: 500 },
    { slug: 'employee-offboardings',            groupKey: 'empresa',         order: 510 },
] as const
