export const ATTENTION_PROGRAM_ERROR_CODES = {
  VAL_INPUT: 'NOM035.PRG.VAL_INPUT',
  ALREADY_OPEN: 'NOM035.PRG.ALREADY_OPEN',
  NOT_FOUND_ORIGIN: 'NOM035.PRG.NOT_FOUND_ORIGIN',
  NOT_FOUND_PROGRAM: 'NOM035.PRG.NOT_FOUND_PROGRAM',
  ACTION_INCOMPLETE: 'NOM035.PRG.ACTION_INCOMPLETE',
  INVALID_DIMENSION: 'NOM035.PRG.INVALID_DIMENSION',
  INVALID_LEVEL: 'NOM035.PRG.INVALID_LEVEL',
  ACTION_NOT_FOUND: 'NOM035.PRG.ACTION_NOT_FOUND',
  PROGRAM_CLOSED: 'NOM035.PRG.PROGRAM_CLOSED',
  FORBIDDEN: 'NOM035.PRG.FORBIDDEN',
  SYS_UNHANDLED: 'NOM035.PRG.SYS_UNHANDLED',
} as const

export type AttentionProgramErrorCode =
  (typeof ATTENTION_PROGRAM_ERROR_CODES)[keyof typeof ATTENTION_PROGRAM_ERROR_CODES]
