export const ATTENTION_PROGRAM_ERROR_CODES = {
  VAL_INPUT: 'NOM035.PRG.VAL_INPUT',
  ALREADY_OPEN: 'NOM035.PRG.ALREADY_OPEN',
  NOT_FOUND_ORIGIN: 'NOM035.PRG.NOT_FOUND_ORIGIN',
  NOT_FOUND_PROGRAM: 'NOM035.PRG.NOT_FOUND_PROGRAM',
  FORBIDDEN: 'NOM035.PRG.FORBIDDEN',
  SYS_UNHANDLED: 'NOM035.PRG.SYS_UNHANDLED',
} as const

export type AttentionProgramErrorCode =
  (typeof ATTENTION_PROGRAM_ERROR_CODES)[keyof typeof ATTENTION_PROGRAM_ERROR_CODES]
