import type { PermissionGateOptions } from '#constants/permission_gate'

const employeesStandard = (
  action: string | readonly string[]
): PermissionGateOptions => ({
  module: 'employees',
  action,
  bypass: 'standard',
})

/**
 * Mapa de declaraciones de permiso de lectura del expediente (USRH1785766406733).
 * Fuente única que consumen las rutas y los controladores de superficie compartida;
 * no concede nada ni enciende la exigencia del módulo.
 */
export const EMPLOYEES_READ_PERMISSION_DECLARATIONS = {
  showEmployee: employeesStandard('tab-trabajo-read'),
  getEmployeeById: employeesStandard('tab-trabajo-read'),
  getEmployeeByPerson: employeesStandard('tab-trabajo-read'),
  getSalaryHistory: employeesStandard('tab-trabajo-read'),
  getEmployeeContracts: employeesStandard('tab-trabajo-read'),
  showEmployeeContract: employeesStandard('tab-trabajo-read'),
  getBranchOfficeHistory: employeesStandard('tab-trabajo-read'),
  indexTemporaryAssignments: employeesStandard('tab-trabajo-read'),
  showActiveTemporaryAssignment: employeesStandard('tab-trabajo-read'),
  getYearsWorked: employeesStandard('tab-trabajo-read'),
  getVacationsUsed: employeesStandard('tab-trabajo-read'),
  getVacationsCorresponding: employeesStandard('tab-trabajo-read'),
  getVacationsByPeriod: employeesStandard('tab-trabajo-read'),
  getVacationDeductions: employeesStandard('tab-trabajo-read'),
  indexEmployeeVacationArchives: employeesStandard('tab-trabajo-read'),
  showEmployeeVacationArchive: employeesStandard('tab-trabajo-read'),
  indexVacationArchiveContents: employeesStandard('tab-trabajo-read'),
  showVacationArchiveContent: employeesStandard('tab-trabajo-read'),
  getVacations: employeesStandard('tab-trabajo-read'),
  getAllVacationsByPeriod: employeesStandard('tab-trabajo-read'),
  indexEmployeeShifts: employeesStandard('tab-trabajo-read'),
  showEmployeeShift: employeesStandard('tab-trabajo-read'),
  getShiftsByEmployee: employeesStandard('tab-trabajo-read'),
  getActiveShiftByEmployee: employeesStandard('tab-trabajo-read'),
  showEmployeeShiftChange: employeesStandard('tab-trabajo-read'),
  getShiftChangesByEmployee: employeesStandard('tab-trabajo-read'),
  indexShiftExceptions: employeesStandard('tab-trabajo-read'),
  showShiftException: employeesStandard('tab-trabajo-read'),
  getShiftExceptionsByEmployee: employeesStandard('tab-trabajo-read'),
  getShiftExceptionEvidences: employeesStandard('tab-trabajo-read'),
  indexShiftExceptionEvidences: employeesStandard('tab-trabajo-read'),
  showShiftExceptionEvidence: employeesStandard('tab-trabajo-read'),
  indexAssistCalendars: employeesStandard('tab-trabajo-read'),
  indexExceptionRequests: employeesStandard('tab-trabajo-read'),
  indexAllExceptionRequests: employeesStandard('tab-trabajo-read'),
  showExceptionRequest: employeesStandard('tab-trabajo-read'),
  indexEmployeeBonuses: employeesStandard('tab-trabajo-read'),
  getBonusConcepts: employeesStandard('tab-trabajo-read'),
  showEmployeeBonus: employeesStandard('tab-trabajo-read'),
  showEmployeeBadge: employeesStandard('tab-foto-read'),
  getEmployeeBadgePdf: employeesStandard('tab-foto-read'),
  getEmployeeBadgePng: employeesStandard('tab-foto-read'),
  showPersonCollaborator: employeesStandard('tab-persona-read'),
  showEmployeeChild: employeesStandard('tab-persona-read'),
  showEmployeeSpouse: employeesStandard('tab-persona-read'),
  showEmployeeEmergencyContact: employeesStandard('tab-persona-read'),
  getEmergencyContactsByEmployee: employeesStandard('tab-persona-read'),
  indexEmployeeAddress: employeesStandard('tab-domicilio-read'),
  showEmployeeAddress: employeesStandard('tab-domicilio-read'),
  getEmployeeBanks: employeesStandard('tab-bancos-read'),
  showEmployeeBank: employeesStandard('tab-bancos-read'),
  indexEmployeeMedicalConditions: employeesStandard('tab-condicion-medica-read'),
  getMedicalConditionsByEmployee: employeesStandard('tab-condicion-medica-read'),
  showEmployeeMedicalCondition: employeesStandard('tab-condicion-medica-read'),
  indexMedicalConditionPropertyValues: employeesStandard('tab-condicion-medica-read'),
  showMedicalConditionPropertyValue: employeesStandard('tab-condicion-medica-read'),
  indexLactationPeriods: employeesStandard('tab-periodos-lactancia-read'),
  lactationComplianceReport: employeesStandard('tab-periodos-lactancia-read'),
  listAllLactationConflicts: employeesStandard('tab-periodos-lactancia-read'),
  listLactationConflicts: employeesStandard('tab-periodos-lactancia-read'),
  indexLactationEvidences: employeesStandard('tab-periodos-lactancia-read'),
  getEmployeeProceedingFiles: employeesStandard('tab-expediente-read'),
  getExpiredExpiringProceedingFiles: employeesStandard('tab-expediente-read'),
  indexEmployeeProceedingFiles: employeesStandard('tab-expediente-read'),
  showEmployeeProceedingFile: employeesStandard('tab-expediente-read'),
  showEmployeeRecord: employeesStandard('tab-expediente-read'),
  getEmployeeRecordCategories: employeesStandard('tab-expediente-read'),
  getProceedingFileTypePropertyCategoriesByEmployee: employeesStandard('tab-expediente-read'),
  getEmployeeConsentStatus: employeesStandard('tab-consentimiento-read'),
  getUserResponsible: employeesStandard('tab-responsable-read'),
  getEmployeesAssigned: employeesStandard('tab-asignados-read'),
  showUserResponsibleEmployee: employeesStandard([
    'tab-responsable-read',
    'tab-asignados-read',
  ]),
  getEmployeeZones: employeesStandard('tab-zonas-read'),
  showEmployeeZone: employeesStandard('tab-zonas-read'),
  indexEmployeeAnnotations: employeesStandard('tab-anotaciones-read'),
  getAnnotationsByEmployee: employeesStandard('tab-anotaciones-read'),
  showEmployeeAnnotation: employeesStandard('tab-anotaciones-read'),
  showEmployeeBiometrics: employeesStandard('tab-biometricos-read'),
  getEmployeeFingers: employeesStandard('tab-biometricos-read'),
  getEmployeeFaceStatus: employeesStandard('tab-biometricos-read'),
  getBiometricFaceId: employeesStandard('tab-biometricos-read'),
  getBiometricFaceIdWithToken: employeesStandard('tab-biometricos-read'),
  streamBiometricFacePhoto: employeesStandard('tab-biometricos-read'),
  getBiometricsList: employeesStandard('tab-biometricos-read'),
  indexEmployeeDevices: employeesStandard('tab-dispositivos-read'),
  getDevicesByEmployee: employeesStandard('tab-dispositivos-read'),
  indexEmployeeEvaluations: employeesStandard('tab-evaluaciones-read'),
  showEmployeeEvaluation: employeesStandard('tab-evaluaciones-read'),
  getEvaluationsByEmployee: employeesStandard('tab-evaluaciones-read'),
  indexCompetencyEvaluations: employeesStandard('tab-evaluaciones-read'),
  showCompetencyEvaluation: employeesStandard('tab-evaluaciones-read'),
  indexKpiEvaluations: employeesStandard('tab-evaluaciones-read'),
  showKpiEvaluation: employeesStandard('tab-evaluaciones-read'),
  indexEmployeeAssessments: employeesStandard('tab-assessments-read'),
  getAssessmentsByEmployee: employeesStandard('tab-assessments-read'),
  showEmployeeAssessment: employeesStandard('tab-assessments-read'),
  indexCareerPathCandidates: employeesStandard('tab-ruta-carrera-read'),
  showCareerPathCandidate: employeesStandard('tab-ruta-carrera-read'),
  getCareerPathByEmployee: employeesStandard('tab-ruta-carrera-read'),
  getEmployeeCertifications: employeesStandard('tab-certificaciones-read'),
  indexCertificationUploads: employeesStandard('tab-certificaciones-read'),
  getExpiredExpiringCertifications: employeesStandard('tab-certificaciones-read'),
  indexEmployeeCertificationsExpiration: employeesStandard('tab-certificaciones-read'),
  indexWorkDisabilities: employeesStandard('read-work-disabilities'),
  showWorkDisability: employeesStandard('read-work-disabilities'),
  getWorkDisabilitiesByEmployee: employeesStandard('read-work-disabilities'),
  showWorkDisabilityPeriod: employeesStandard('read-work-disabilities'),
  showWorkDisabilityNote: employeesStandard('read-work-disabilities'),
  showWorkDisabilityPeriodExpense: employeesStandard('read-work-disabilities'),
  getDaysWorkDisability: employeesStandard('read-work-disabilities'),
  getDaysWorkDisabilityAll: employeesStandard('read-work-disabilities'),
} as const satisfies Record<string, PermissionGateOptions>

export const EMPLOYEES_PERSON_COLLABORATOR_READ_PERMISSION: PermissionGateOptions =
  employeesStandard('tab-persona-read')

export const EMPLOYEES_PROCEEDING_FILE_EMPLOYEE_AREA_READ_PERMISSION: PermissionGateOptions =
  employeesStandard('tab-expediente-read')

