/**
 * Códigos de error de la configuración de niveles por puesto
 * (USRH1785273891313). Prefijo del área: ORG.POSLEVELCFG (spec §6).
 */
export const POSITION_POSITION_LEVEL_ERROR_CODES = {
  VAL_INPUT: 'ORG.POSLEVELCFG.VAL_INPUT',
  LEVEL_SOURCE_AMBIGUOUS: 'ORG.POSLEVELCFG.LEVEL_SOURCE_AMBIGUOUS',
  AD_HOC_NAME_REQUIRED: 'ORG.POSLEVELCFG.AD_HOC_NAME_REQUIRED',
  DUPLICATE_LEVEL: 'ORG.POSLEVELCFG.DUPLICATE_LEVEL',
  LEVEL_NOT_IN_CATALOG: 'ORG.POSLEVELCFG.LEVEL_NOT_IN_CATALOG',
  MULTIPLE_DEFAULT: 'ORG.POSLEVELCFG.MULTIPLE_DEFAULT',
  DEFAULT_ON_INACTIVE: 'ORG.POSLEVELCFG.DEFAULT_ON_INACTIVE',
  LEVEL_HAS_EMPLOYEES: 'ORG.POSLEVELCFG.LEVEL_HAS_EMPLOYEES',
  POSITION_NOT_FOUND: 'ORG.POSLEVELCFG.POSITION_NOT_FOUND',
  FORBIDDEN: 'ORG.POSLEVELCFG.FORBIDDEN',
  SYS_UNHANDLED: 'ORG.POSLEVELCFG.UNEXPECTED',
} as const

export type PositionPositionLevelErrorCode =
  (typeof POSITION_POSITION_LEVEL_ERROR_CODES)[keyof typeof POSITION_POSITION_LEVEL_ERROR_CODES]
