export const QUESTIONNAIRE_APPLICATION_ERROR_CODES = {
  VAL_INPUT: 'NOM035.QRUN.VAL_INPUT',
  NOT_APPLICABLE: 'NOM035.QRUN.NOT_APPLICABLE',
  NOT_FOUND_BRANCH: 'NOM035.QRUN.NOT_FOUND_BRANCH',
  ALREADY_OPEN: 'NOM035.QRUN.ALREADY_OPEN',
  FORBIDDEN: 'NOM035.QRUN.FORBIDDEN',
  NOT_FOUND: 'NOM035.QRUN.NOT_FOUND',
  ALREADY_CLOSED: 'NOM035.QRUN.ALREADY_CLOSED',
  NOT_IN_PROGRESS: 'NOM035.QRUN.NOT_IN_PROGRESS',
  HAS_RESPONSES: 'NOM035.QRUN.HAS_RESPONSES',
  INCOMPLETE_ANSWERS: 'NOM035.QRUN.INCOMPLETE_ANSWERS',
  INVALID_ANSWER_OPTION: 'NOM035.QRUN.INVALID_ANSWER_OPTION',
  APPLICATION_CLOSED: 'NOM035.QRUN.APPLICATION_CLOSED',
  ALREADY_ANSWERED: 'NOM035.QRUN.ALREADY_ANSWERED',
  TARGET_NOT_FOUND: 'NOM035.QRUN.TARGET_NOT_FOUND',
  FOLIO_GENERATION_FAILED: 'NOM035.QRUN.FOLIO_GENERATION_FAILED',
  SYS_UNHANDLED: 'NOM035.QRUN.SYS_UNHANDLED',
} as const

export type QuestionnaireApplicationErrorCode =
  (typeof QUESTIONNAIRE_APPLICATION_ERROR_CODES)[keyof typeof QUESTIONNAIRE_APPLICATION_ERROR_CODES]
